[package]
name = "desktop"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.4", features = [] }

[dependencies]
anyhow = "1.0"
tauri = { version = "1.4", features = [ "macos-private-api", "window-set-resizable", "window-set-always-on-top", "window-set-skip-taskbar", "window-set-position", "window-set-size", "cli", "shell-open", "dialog"] }
tauri-plugin-single-instance = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sysinfo = "0.29.10"

[features]
# This feature is used for production builds or when `devPath` points to the
# filesystem. Do not remove!
custom-protocol = ["tauri/custom-protocol"]
