[package]
name = "desktop"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.0-alpha.11", features = [] }

[dependencies]
anyhow = "1.0"
async-trait = "0.1.74"
clap = { version = "4.4.8", features = ["derive"] }
reqwest = { version = "0.11.22", features = ["json"] }
tauri = { version = "2.0.0-alpha.17", features = ["macos-private-api"] }
tauri-plugin-http = "2.0.0-alpha.5"
tauri-plugin-shell = "2.0.0-alpha.4"
tauri-plugin-single-instance = "2.0.0-alpha.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
starship-battery = "0.8.2"
sysinfo = "0.29.10"
tokio = { version = "1.33.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.17"

[features]
# This feature is used for production builds or when `devPath` points to the
# filesystem. Do not remove!
custom-protocol = ["tauri/custom-protocol"]
