# Thanks for trying out zebar :)
# Yaml is white-space sensitive BTW (use 2 spaces to indent).

##
# Settings to apply to all windows, popups, and desktop widgets.
# Docs regarding global: https://some-future-docs-link.com
##
global:
  # CSS/SCSS to apply to the root document (ie. the <html> element).
  root_styles: |
    --some-var: blue;
  # Path to CSS or SCSS file(s). Loaded after inline styles.
  load_stylesheets: []
  # Path to JS file(s). Loaded after mounting window element.
  load_scripts: []

##
# Docs regarding window: https://some-future-docs-link.com
##
window/bar:
  providers: ['self']
  # Width of the window in physical pixels.
  width: '{{ self.args.MONITOR_WIDTH }}'
  # Height of the window in physical pixels.
  height: '50'
  # X-position of the window in physical pixels.
  position_x: '{{ self.args.MONITOR_X }}'
  # Y-position of the window in physical pixels.
  position_y: '{{ self.args.MONITOR_Y }}'
  # Whether to show the window above all others.
  always_on_top: false
  # Whether the window should be shown in the taskbar.
  show_in_taskbar: false
  # Whether the window should have resize handles.
  resizable: false
  # CSS/SCSS styles to apply to the window element.
  styles: |
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    height: 100%;
    background: #20242cc4;
    color: #ffffff;
    font-family: Segoe UI;
    font-size: 13px;
    padding: 4px 6px;
  group/left:
    styles: |
      display: flex;
    template/glazewm:
      providers: ['glazewm']
      template: |
        @for (workspace of glazewm.workspaces) {
          <button class="{{ workspace.state }}-workspace">
            {{ workspace.name }}
          </button>
        }
    template/clock:
      providers: ['date']
      template: |
        {{ date.toFormat(date.now, 'yyyy') }}

  group/center:
    template/ip:
      providers: ['ip']
      template: |
        {{ ip.address }}

  group/right:
    template/weather:
      providers: ['weather']
      template: |
        {{ weather.status }} {{weather.celsiusTemp}}
