# Thanks for trying out Zanbar :)
# Yaml is white-space sensitive BTW (always use 2 spaces).

##
# Docs regarding general: https://some-future-docs-link.com
##
general:
  # CSS/SCSS to apply to the root document. Styles defined here will apply
  # to all bars and popups.
  global_styles: |
    --some-var: blue;
  # Path to CSS or SCSS file with global styles. Is merged with
  # styles defined in `general.global_styles`.
  global_stylesheet_path: ./custom.scss

##
# Docs regarding bar: https://some-future-docs-link.com
##
bar/default:
  # Width of the bar in physical pixels.
  width: '{{ env.screen_width }}'
  # Height of the bar in physical pixels.
  height: '200'
  # X-position of the bar in physical pixels.
  position_x: '{{ env.screen_x }}'
  # Y-position of the bar in physical pixels.
  position_y: '{{ env.screen_y }}'
  # Whether to show the bar above all other windows.
  always_on_top: true
  # Whether the bar should be shown in the taskbar.
  show_in_taskbar: false
  # Whether the bar should have resize handles.
  resizable: false
  # CSS/SCSS styles to apply to the bar element.
  styles: |
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    background: #20242cc4;
    color: #ffffff;
    font-family: Segoe UI;
    font-size: 13px;
    padding: 4px 6px;
  group/left:
    styles: |
      display: flex;
    components:
      - providers: ['date_time']
        template: |
          {{ date_time.hours }}:{{ date_time.minutes }}
      - providers: ['cpu']
        template: |
          {{ cpu.temp }}
  group/center:
    components:
      - providers: ['date_time']
        template: |
          {{ date_time.now }}
  group/right:
    components:
      - providers: ['date_time']
        template: |
          {{ date_time.now }}
