# Thanks for trying out Zanbar!
# Yaml is white-space sensitive btw (always use 2 spaces).

# Docs re. general: https://some-future-docs-link.com
general:
  # X-position of the bar in physical pixels.
  position_x: '{{ vars.screen_x }} - 10px'
  # Y-position of the bar in physical pixels.
  position_y: '{{ vars.screen_y }} - 10px'
  # Width of the bar in physical pixels.
  width: '{{ vars.screen_width }}'
  # Height of the bar in physical pixels.
  height: '30px'
  # Whether bar window should be transparent. Can be combined with `opacity`
  # or a semi-transparent `background-color` in the bar styles for semi-
  # transparent windows.
  transparent: false
  # Whether to enable devtools. Can be launched by focusing the bar
  # window and pressing f12.
  enable_devtools: false
  # Is merged with styles defined in `general.global_stylesheet_url`.
  global_styles: |
    --some-var: blue;
  # Path to CSS or SCSS file with global styles. Is merged with
  # styles defined in `general.global_styles`.
  global_stylesheet_path: ./custom.scss

# Docs re. bar: https://some-future-docs-link.com
bar/default:
  styles: |
    background: #20242cc4;
    color: #ffffff;
    font-family: Segoe UI;
    font-size: 13px;
    padding: 4px 6px;
  group/left:
    styles: |
      display: flex;
    components:
      - type: 'clock'
      - type: 'cpu'
  group/center:
    components:
      - type: 'clock'
  group/right:
    components:
      - type: 'clock'
