# Thanks for trying out Zanbar :)
# Yaml is white-space sensitive BTW (use 2 spaces to indent).

##
# Settings to apply to all windows, popups, and desktop widgets.
# Docs regarding global: https://some-future-docs-link.com
##
global:
  # CSS/SCSS to apply to the root document (ie. the <html> element).
  root_styles: |
    --some-var: blue;
  # Path to CSS or SCSS file(s). Loaded after inline styles.
  load_stylesheets: []
  # Path to JS file(s). Loaded after mounting bar element.
  load_scripts: []

##
# Docs regarding bar: https://some-future-docs-link.com
##
bar/default:
  # Width of the bar in physical pixels.
  width: '{{ env.screen_width }}'
  # Height of the bar in physical pixels.
  height: '50'
  # X-position of the bar in physical pixels.
  position_x: '{{ env.screen_x }}'
  # Y-position of the bar in physical pixels.
  position_y: '{{ env.screen_y }}'
  # Whether to show the bar above all other windows.
  always_on_top: false
  # Whether the bar should be shown in the taskbar.
  show_in_taskbar: false
  # Whether the bar should have resize handles.
  resizable: false
  # CSS/SCSS styles to apply to the bar element.
  styles: |
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    height: 100%;
    background: #20242cc4;
    color: #ffffff;
    font-family: Segoe UI;
    font-size: 13px;
    padding: 4px 6px;
  group/left:
    styles: |
      display: flex;
    components:
      - providers: ['glazewm']
        template: |
          @for (workspace of glazewm.workspaces) {
            @if (workspace.state == 'focused') {
              <button class="focused-workspace">
                {{ workspace.name }}
              </button>
            } @else if (workspace.state == 'active') {
              <button class="active-workspace">
                {{ workspace.name }}
              </button>
            } @else {
              <button class="normal-workspace">
                {{ workspace.name }}
              </button>
            }
          }
      - providers: ['date_time']
        template: |
          {{ date_time.hours }}:{{ date_time.minutes }}
  group/center:
    components:
      - providers: ['ip']
        template: |
          {{ ip.ip_address }}
  group/right:
    components:
      - providers: ['weather']
        template: |
          {{ weather.status }} {{weather.celsius_temp}}
